version: 2

build:
  os: ubuntu-lts-latest
  apt_packages:
    - libpulse0
    - p7zip-full
    - libasound2
    - libssl-dev
  tools:
    python: "3.11"
  jobs:
    post_install:
      - "pip install .[docs]"
      - "pip install hatch"
      - "hatch run sdk-download"

sphinx:
  configuration: docs/conf.py
